### ISSUE TITLE
Wow 

### ISSUE THREAD

**Issue by AgarioCheats** [camilleeyries/Acteur-agario-client-Aim-Bot#1]
I'll delete this afterwards, BUT ARE YOU ERALLY 12 YEARS OLD!?!??!?! IF SO YOU'RE AMAZINGLY TALENTED!!!

**Comment by clouedoc** [comment]
Yes i have 12 year old :D. My first Word is "allô ?" XD.My father is programmer iOS (jeyries.fr) and it has fascinated me then..I started to learn html to 9-10 years then this is where I am :)
